module.exports = {
  plumber: [
    "plumbing",
    "pipe",
    "leak",
    "drain",
    "clog",
    "clogged drain",
    "sink",
    "tap",
    "faucet",
    "toilet",
    "sewer",
    "pipe blockage",
    "plumber",
    "tap repair",
    "bathroom leak",
    "blocked drain",
    "pipe burst",
    "leaky pipe",
    "overflow",
    "water backup",
    "slow drain",
    "drain cleaner",
    "pipe leak",
    "water leak",
  ],
  electrician: [
    "electrical",
    "wiring",
    "fuse",
    "socket",
    "outlet",
    "circuit",
    "breaker",
    "electric panel",
    "short circuit",
    "light switch",
    "electrician",
    "ac power socket",
    "circuit breaker",
  ],
  hvac: [
    "ac",
    "air conditioner",
    "air conditioning",
    "air conditioning unit",
    "ac unit",
    "split ac",
    "ductless air conditioner",
    "ac repair",
    "broken ac",
    "outdoor unit",
    "damaged ac",
    "vent",
    "hvac",
    "heat pump",
    "heater",
    "furnace",
    "ventilation",
    "thermostat",
    "hvac technician",
    "burnt ac",
    "condensate",
    "freon leak",
    "hvac system",
    "air flow",
    "furnace repair",
    "heating, ventilation, and air conditioning",
  ],
  applianceRepair: [
    "appliance",
    "washing",
    "washer",
    "washing machine",
    "dryer",
    "refrigerator",
    "microwave",
    "electric range",
    "range",
    "stove",
    "oven",
    "dishwasher",
    "ice maker",
    "freezer",
    "appliance repair",
    "major appliance",
    "broken appliance",
    "damaged washer",
    "noisy dryer",
    "appliance issue",
  ],
  glazier: [
    "glass",
    "mirror",
    "broken mirror",
    "crack",
    "window pane",
    "shattered",
    "window glass",
    "glass door",
    "mirror repair",
    "cracked glass",
    "glass repair",
  ],
  handyman: [
    "window",
    "hinge",
    "cabinet",
    "shelf",
    "tv mount",
    "furniture assembly",
    "light fixture",
    "odd jobs",
    "small repairs",
    "curtain rod",
    "door adjustment",
    "handle replacement",
    "handyman",
  ],

  locksmith: [
    "lock",
    "key",
    "door lock",
    "lost key",
    "locksmith",
    "unlock",
    "deadbolt",
    "safe",
    "car lockout",
    "lock replacement",
    "key duplication",
    "lock rekey",
    "key stuck",
  ],
  pestControl: [
    "pest",
    "cockroach",
    "ant",
    "rodent",
    "rat",
    "mouse",
    "termite",
    "bug infestation",
    "insect",
    "spider",
    "bed bug",
    "exterminator",
    "infestation",
  ],
  landscaping: [
    "yard",
    "grass",
    "mowing",
    "tree",
    "tree trimming",
    "hedge",
    "lawn",
    "garden",
    "landscaping",
    "mulch",
    "planting",
    "weed removal",
    "outdoor cleanup",
    "landscape design",
  ],
  roofing: [
    "roof",
    "roof leak",
    "roof repair",
    "roof damage repair",
    "roof shingle",
    "shingles",
    "gutter",
    "downspout",
    "roofing",
    "tile roof",
    "roof tiles",
    "flashing",
    "roof replacement",
  ],
  waterproofing: [
    "basement waterproofing",
    "foundation",
    "foundation crack",
    "foundation repair",
    "foundation wall",
    "structural crack",
    "masonry crack",
    "water seepage",
    "sump pump",
    "crawl space",
    "flooded basement",
    "efflorescence",
    "bowed wall",
    "waterproofing",
    "leaky basement",
    "wet basement",
    "mold",
    "mildew",
    "black mold",
    "mold remediation",
    "indoor mold",
    "basement sump pump",
    "moist",
  ],
  painting: [
    "paint",
    "painting",
    "repaint",
    "wall paint",
    "house paint",
    "exterior paint",
    "ceiling paint",
    "paint job",
    "painter",
    "paint touch-up",
  ],
  autoRepair: [
    "car",
    "vehicle",
    "engine",
    "brake",
    "battery",
    "auto repair",
    "mechanic",
    "oil change",
    "flat tire",
    "check engine",
    "vehicle repair",
    "car service",
    "auto service",
    "car engine",
  ],
  garageDoorRepair: [
    "garage door",
    "garage door opener",
    "garage motor",
    "garage spring",
    "garage door repair",
    "garage door track",
    "garage sensor",
    "garage door remote",
    "garage jammed",
    "garage stuck",
    "broken garage",
  ],
};
